apiVersion: v1
kind: Template
labels:
  template: jenkins-continuous-infra-slave-builder
metadata:
  annotations:
    description: continuous-infra Slaves
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jenkins-continuous-infra-slave-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      slave-directory: /var/lib/jenkins
    labels:
      role: jenkins-slave
    name: jenkins-continuous-infra-slave
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: jenkins-continuous-infra-slave
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-continuous-infra-slave:latest
    resources: {}
    source:
      contextDir: ${SLAVE_REPO_CONTEXTDIR}
      git:
        ref: ${SLAVE_REPO_REF}
        uri: ${SLAVE_REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Label for slave pods which are used by Jenkins to discover slave pods and assign jobs to them
  displayName: Jenkins Slave Label
  name: SLAVE_LABEL
  required: true
  value: jdk8
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: SLAVE_REPO_URL
  value: https://github.com/scoheb/jenkins-s2i-example.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: SLAVE_REPO_CONTEXTDIR
  value: slave
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: SLAVE_REPO_REF
  value: master
